### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by davidwaroquiers** [Acetylsalicylsaeure/pymopac#1]
Hello @Acetylsalicylsaeure 

I wanted to interact with you about pymopac. We are willing to develop a python interface for mopac and before doing that we looked up if there was already something existing. I'd like to have a quick chat/exchange with you about this. If you agree, what would be the preferred channel of communication ? (i.e. linkedin, mail, ... ?)

Thanks a lot!

Best,

David

**Comment by Acetylsalicylsaeure** [comment]
Dear David,

I'm curious to hear what you have planned! I sent you a conncection request on LinkedIn, you can find my profile in my GitHub bio now.

See you there,
Paul
